#!/bin/bash

hour=$(date +'%H')
path=$(pwd)/wallpapers/
if [ $hour -lt 6 ]; then
wal -i $(find $path"4"/ -type f | shuf -n1)
elif [ $hour -lt 10 ]; then
wal -i $(find $path"2" /-type f | shuf -n1)
elif [ $hour -lt 14 ]; then
wal -i $(find $path"1"/ -type f | shuf -n1)
elif [ $hour -lt 16 ]; then
wal -i $(find $path"2"/ -type f | shuf -n1)
elif [ $hour -lt 18 ]; then
wal -i $(find $path"2"/ -type f | shuf -n1)
elif [ $hour -lt 22 ]; then
wal -i $(find $path"3"/ -type f | shuf -n1)
else
wal -i $(find $path"4"/ -type f | shuf -n1)
fi
